services:
  ml-service:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "5000:5000"
    volumes:
      - ./Machine_Learning/models:/app/models
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - ml-service
    environment:
      - NODE_ENV=production
    restart: unless-stopped